# -*- coding: utf-8 -*-
"""MSAI631_Traditional_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Hp_4jw_9Y_z6t1LwNnhBI8nA1gV6kBl
"""

print("Welcome to SaiBot!")
print("Type 'help' to see what I can do.")
print("Type 'exit' to end the chat.\n")

def chatbot():
    while True:
        user_input = input("You: ").lower().strip()

        if user_input == "exit":
            print("SaiBot: Goodbye! Have a great day.")
            break

        elif user_input == "help":
            print("""
SaiBot Capabilities:
- Say hello
- Tell time
- Discuss AI and HCI
- Answer course questions
- Respond to greetings
- Handle unknown questions
            """)

        elif "hello" in user_input or "hi" in user_input:
            print("SaiBot: Hello! How can I help you today?")

        elif "how are you" in user_input:
            print("SaiBot: I'm functioning properly! Thanks for asking.")

        elif "time" in user_input:
            from datetime import datetime
            current_time = datetime.now().strftime("%I:%M %p")
            print(f"SaiBot: Current time is {current_time}")

        elif "hci" in user_input:
            print("SaiBot: HCI stands for Human-Computer Interaction.")

        elif "ai" in user_input:
            print("SaiBot: AI means Artificial Intelligence.")

        elif "course" in user_input:
            print("SaiBot: This chatbot supports MSAI 631 learning concepts.")

        else:
            print("SaiBot: Sorry, I didn't understand that. Please try again or type 'help'.")

chatbot()